[project]
name = "nonebot-plugin-mccheck"
version = "0.1.8.1"
description = "Minecraft服务器状态查询，支持IPv6"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "molanp", email = "luotian233@foxmail.com" },
]
dependencies = [
    "pillow>=10.2.0",
    "nonebot2[fastapi]>=2.2.0",
    "nonebot-adapter-onebot>=2.4.1",
    "aiodns",
    "ujson"
]
license = { text = "GPL-3.0" }

[project.urls]
homepage = "https://github.com/molanp/nonebot_plugin_mccheck"
repository = "https://github.com/molanp/nonebot_plugin_mccheck"

[project.optional-dependencies]
adapters = [
    "nonebot-adapter-onebot>=2.4.1",
]

[tool.poetry]
packages = [
    { include = "nonebot_plugin_mccheck" },
    { include = "nonebot_plugin_mccheck.font" }
]


[tool.poetry.include]
files = [
    "nonebot_plugin_mccheck/font/**/*",
    "README.md",
    "LICENSE"
]